### ISSUE TITLE
Drop execution permission on files

### ISSUE THREAD

**Issue by sthibaul** [mbrola/mbrola-voices#4]
Hello,

Some files have execution permissions for no reason, for instance:

-rwxr-xr-x 1 samy samy 1,6K avril 18 21:25 license.txt

that could be disabled.

Samuel

**Comment by valdisvi** [comment]
What about folders (some have 777, some 755) and general mask for files (some have 664, some 644)?

**Comment by sthibaul** [comment]
folders should be 755 and files should be 644

**Comment by valdisvi** [comment]
I checked that permissions are ok.
