### ISSUE TITLE
Links to original MBROLA site are dead.

### ISSUE THREAD

**Issue by indiamcq** [mbrola/mbrola-voices#5]
All the links to the http://tcts.fpms.ac.be/ domain no longer work. Wayback Machine has data up to Dec 2018 but pages are missing in 2019.

Is there a replacement site?

Ian

**Comment by valdisvi** [comment]
It seems, site is reorganized, but all relevant sites to MBROLA are working.

**Comment by polyzen** [comment]
This is an issue again.

Should they not be changed to point to https://github.com/numediart/MBROLA? Especially the links in the licenses that say:
```
Permission is granted to use this database for synthesizing speech with and only with MBROLA program made available from the MBROLA project web page:

http://tcts.fpms.ac.be/synthesis/mbrola.html
```

Another question, would that then make them AGPL?

**Comment by valdisvi** [comment]
Address in provided info is [changed](https://github.com/numediart/MBROLA/commit/20a047d61ff1acb0e3a998506727ea87689b4aae) to https://github.com/numediart/MBROLA/.

**Comment by polyzen** [comment]
I don't understand what that accomplishes. The rest of the links have to be updated too, no?

**Comment by valdisvi** [comment]
Oh, you probably meant all old links in license files. I [updated them](https://github.com/valdisvi/MBROLA-voices/commit/fe05a0ccef6a941207fd6aaad0b31294a1f93a51) to https://github.com/numediart/MBROLA. There are still few binary database files which have old links compiled into them.

**Comment by polyzen** [comment]
> Oh, you probably meant all old links in license files. I updated them to https://github.com/numediart/MBROLA.

I did. Thank you very much!

For licenses that say "The distribution of this database is submitted to the same terms and conditions as the distribution of the Mbrola program." does that mean they are now AGPL?

> There are still few binary database files which have old links compiled into them.

Can these still not be distributed alongside MBROLA sourced from https://github.com/numediart/MBROLA?
