### ISSUE TITLE
mbrola return: This program can't decode your database

### ISSUE THREAD

**Issue by SeRal79** [mbrola/mbrola-voices#7]
last lines make:

READ: B-a* 1037 2351 1383 end_raw=316440 2595 nb_frame=11 physical=11
READ: B-a2 1106 4978 2074 end_raw=320520 2628 nb_frame=33 physical=34
READ: _-k 2181 3665 3181 end_raw=322200 2641 nb_frame=13 physical=14
READ: k-a 2420 5048 4425 end_raw=324960 2663 nb_frame=22 physical=23
READ: k-a* 3665 6559 5255 end_raw=328080 2688 nb_frame=25 physical=26
READ: k-a2 1452 5601 3595 end_raw=332520 2723 nb_frame=35 physical=37
Ooops on line (.seg file) : 
NO _-_ diphone, automatically adds it
_-_: _-_ 1452 5601 3595 end_raw=337440 2763 nb_frame=40
NO DIPHONE COPIES!
Built on lun oct 19 16:50:56 -05 2020
F0 FILE esco1.f0 DETECTED
MBE FILE esco1.mbe DETECTED
SYN FILE esco1.syn DETECTED

**Comment by valdisvi** [comment]
With information given, this issue looks like spam. Can you explain, what exactly issue is?

**Comment by SeRal79** [comment]
mbrola cannot read it, giving the following message:

$mbrola esco1 fonetica.pho test.wav
This program can't decode your database


when I compile everything seems correct:

last lines
$make -f esco1.mak:

READ: B-a* 1037 2351 1383 end_raw=316440 2595 nb_frame=11 physical=11
READ: B-a2 1106 4978 2074 end_raw=320520 2628 nb_frame=33 physical=34
READ: _-k 2181 3665 3181 end_raw=322200 2641 nb_frame=13 physical=14
READ: k-a 2420 5048 4425 end_raw=324960 2663 nb_frame=22 physical=23
READ: k-a* 3665 6559 5255 end_raw=328080 2688 nb_frame=25 physical=26
READ: k-a2 1452 5601 3595 end_raw=332520 2723 nb_frame=35 physical=37
Ooops on line (.seg file) :
NO - diphone, automatically adds it
-: - 1452 5601 3595 end_raw=337440 2763 nb_frame=40
NO DIPHONE COPIES!
Built on lun oct 19 16:50:56 -05 2020
F0 FILE esco1.f0 DETECTED
MBE FILE esco1.mbe DETECTED
SYN FILE esco1.syn DETECTED

**Comment by SeRal79** [comment]
solution
in opensuse 15.2 
zypper in gcc-32bit, gcc7-32bit, gcc7-c++-32bit, gcc-c++-32bit, gdbm-devel-32bit, glibc-32bit

in makefile files add:
CFLAGS += -m32

make clean
make

test in mbrola: OK
